// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceproduct"
)

// BalanceProductCreate is the builder for creating a BalanceProduct entity.
type BalanceProductCreate struct {
	config
	mutation *BalanceProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *BalanceProductCreate) SetName(v string) *BalanceProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BalanceProductCreate) SetDescription(v string) *BalanceProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableDescription(v *string) *BalanceProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *BalanceProductCreate) SetPrice(v float64) *BalanceProductCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BalanceProductCreate) SetAmount(v float64) *BalanceProductCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *BalanceProductCreate) SetOriginalPrice(v float64) *BalanceProductCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableOriginalPrice(v *float64) *BalanceProductCreate {
	if v != nil {
		_c.SetOriginalPrice(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *BalanceProductCreate) SetTags(v string) *BalanceProductCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableTags(v *string) *BalanceProductCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *BalanceProductCreate) SetFeatures(v string) *BalanceProductCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableFeatures(v *string) *BalanceProductCreate {
	if v != nil {
		_c.SetFeatures(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *BalanceProductCreate) SetProductName(v string) *BalanceProductCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableProductName(v *string) *BalanceProductCreate {
	if v != nil {
		_c.SetProductName(*v)
	}
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *BalanceProductCreate) SetForSale(v bool) *BalanceProductCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableForSale(v *bool) *BalanceProductCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (_c *BalanceProductCreate) SetPurchaseLimit(v int) *BalanceProductCreate {
	_c.mutation.SetPurchaseLimit(v)
	return _c
}

// SetNillablePurchaseLimit sets the "purchase_limit" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillablePurchaseLimit(v *int) *BalanceProductCreate {
	if v != nil {
		_c.SetPurchaseLimit(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *BalanceProductCreate) SetSortOrder(v int) *BalanceProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableSortOrder(v *int) *BalanceProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceProductCreate) SetCreatedAt(v time.Time) *BalanceProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableCreatedAt(v *time.Time) *BalanceProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalanceProductCreate) SetUpdatedAt(v time.Time) *BalanceProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BalanceProductCreate) SetNillableUpdatedAt(v *time.Time) *BalanceProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BalanceProductMutation object of the builder.
func (_c *BalanceProductCreate) Mutation() *BalanceProductMutation {
	return _c.mutation
}

// Save creates the BalanceProduct in the database.
func (_c *BalanceProductCreate) Save(ctx context.Context) (*BalanceProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceProductCreate) SaveX(ctx context.Context) *BalanceProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceProductCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := balanceproduct.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := balanceproduct.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.Features(); !ok {
		v := balanceproduct.DefaultFeatures
		_c.mutation.SetFeatures(v)
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		v := balanceproduct.DefaultProductName
		_c.mutation.SetProductName(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := balanceproduct.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.PurchaseLimit(); !ok {
		v := balanceproduct.DefaultPurchaseLimit
		_c.mutation.SetPurchaseLimit(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := balanceproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balanceproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := balanceproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceProductCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BalanceProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := balanceproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "BalanceProduct.description"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "BalanceProduct.price"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "BalanceProduct.amount"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "BalanceProduct.tags"`)}
	}
	if _, ok := _c.mutation.Features(); !ok {
		return &ValidationError{Name: "features", err: errors.New(`ent: missing required field "BalanceProduct.features"`)}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "BalanceProduct.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := balanceproduct.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "BalanceProduct.for_sale"`)}
	}
	if _, ok := _c.mutation.PurchaseLimit(); !ok {
		return &ValidationError{Name: "purchase_limit", err: errors.New(`ent: missing required field "BalanceProduct.purchase_limit"`)}
	}
	if v, ok := _c.mutation.PurchaseLimit(); ok {
		if err := balanceproduct.PurchaseLimitValidator(v); err != nil {
			return &ValidationError{Name: "purchase_limit", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.purchase_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "BalanceProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalanceProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BalanceProduct.updated_at"`)}
	}
	return nil
}

func (_c *BalanceProductCreate) sqlSave(ctx context.Context) (*BalanceProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceProductCreate) createSpec() (*BalanceProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balanceproduct.Table, sqlgraph.NewFieldSpec(balanceproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(balanceproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(balanceproduct.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(balanceproduct.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(balanceproduct.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(balanceproduct.FieldOriginalPrice, field.TypeFloat64, value)
		_node.OriginalPrice = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(balanceproduct.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(balanceproduct.FieldFeatures, field.TypeString, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(balanceproduct.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(balanceproduct.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.PurchaseLimit(); ok {
		_spec.SetField(balanceproduct.FieldPurchaseLimit, field.TypeInt, value)
		_node.PurchaseLimit = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(balanceproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balanceproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceProduct.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceProductCreate) OnConflict(opts ...sql.ConflictOption) *BalanceProductUpsertOne {
	_c.conflict = opts
	return &BalanceProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceProductCreate) OnConflictColumns(columns ...string) *BalanceProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceProductUpsertOne{
		create: _c,
	}
}

type (
	// BalanceProductUpsertOne is the builder for "upsert"-ing
	//  one BalanceProduct node.
	BalanceProductUpsertOne struct {
		create *BalanceProductCreate
	}

	// BalanceProductUpsert is the "OnConflict" setter.
	BalanceProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *BalanceProductUpsert) SetName(v string) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateName() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *BalanceProductUpsert) SetDescription(v string) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateDescription() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldDescription)
	return u
}

// SetPrice sets the "price" field.
func (u *BalanceProductUpsert) SetPrice(v float64) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdatePrice() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *BalanceProductUpsert) AddPrice(v float64) *BalanceProductUpsert {
	u.Add(balanceproduct.FieldPrice, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *BalanceProductUpsert) SetAmount(v float64) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateAmount() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *BalanceProductUpsert) AddAmount(v float64) *BalanceProductUpsert {
	u.Add(balanceproduct.FieldAmount, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *BalanceProductUpsert) SetOriginalPrice(v float64) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateOriginalPrice() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BalanceProductUpsert) AddOriginalPrice(v float64) *BalanceProductUpsert {
	u.Add(balanceproduct.FieldOriginalPrice, v)
	return u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BalanceProductUpsert) ClearOriginalPrice() *BalanceProductUpsert {
	u.SetNull(balanceproduct.FieldOriginalPrice)
	return u
}

// SetTags sets the "tags" field.
func (u *BalanceProductUpsert) SetTags(v string) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateTags() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldTags)
	return u
}

// SetFeatures sets the "features" field.
func (u *BalanceProductUpsert) SetFeatures(v string) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateFeatures() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldFeatures)
	return u
}

// SetProductName sets the "product_name" field.
func (u *BalanceProductUpsert) SetProductName(v string) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateProductName() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldProductName)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *BalanceProductUpsert) SetForSale(v bool) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateForSale() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldForSale)
	return u
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *BalanceProductUpsert) SetPurchaseLimit(v int) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldPurchaseLimit, v)
	return u
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdatePurchaseLimit() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldPurchaseLimit)
	return u
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *BalanceProductUpsert) AddPurchaseLimit(v int) *BalanceProductUpsert {
	u.Add(balanceproduct.FieldPurchaseLimit, v)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *BalanceProductUpsert) SetSortOrder(v int) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateSortOrder() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalanceProductUpsert) AddSortOrder(v int) *BalanceProductUpsert {
	u.Add(balanceproduct.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceProductUpsert) SetUpdatedAt(v time.Time) *BalanceProductUpsert {
	u.Set(balanceproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceProductUpsert) UpdateUpdatedAt() *BalanceProductUpsert {
	u.SetExcluded(balanceproduct.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceProductUpsertOne) UpdateNewValues() *BalanceProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balanceproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceProductUpsertOne) Ignore() *BalanceProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceProductUpsertOne) DoNothing() *BalanceProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceProductCreate.OnConflict
// documentation for more info.
func (u *BalanceProductUpsertOne) Update(set func(*BalanceProductUpsert)) *BalanceProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BalanceProductUpsertOne) SetName(v string) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateName() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BalanceProductUpsertOne) SetDescription(v string) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateDescription() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *BalanceProductUpsertOne) SetPrice(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BalanceProductUpsertOne) AddPrice(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdatePrice() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdatePrice()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceProductUpsertOne) SetAmount(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceProductUpsertOne) AddAmount(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateAmount() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateAmount()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *BalanceProductUpsertOne) SetOriginalPrice(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BalanceProductUpsertOne) AddOriginalPrice(v float64) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateOriginalPrice() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BalanceProductUpsertOne) ClearOriginalPrice() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetTags sets the "tags" field.
func (u *BalanceProductUpsertOne) SetTags(v string) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateTags() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateTags()
	})
}

// SetFeatures sets the "features" field.
func (u *BalanceProductUpsertOne) SetFeatures(v string) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateFeatures() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateFeatures()
	})
}

// SetProductName sets the "product_name" field.
func (u *BalanceProductUpsertOne) SetProductName(v string) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateProductName() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateProductName()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalanceProductUpsertOne) SetForSale(v bool) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateForSale() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateForSale()
	})
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *BalanceProductUpsertOne) SetPurchaseLimit(v int) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetPurchaseLimit(v)
	})
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *BalanceProductUpsertOne) AddPurchaseLimit(v int) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddPurchaseLimit(v)
	})
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdatePurchaseLimit() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdatePurchaseLimit()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalanceProductUpsertOne) SetSortOrder(v int) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalanceProductUpsertOne) AddSortOrder(v int) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateSortOrder() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceProductUpsertOne) SetUpdatedAt(v time.Time) *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceProductUpsertOne) UpdateUpdatedAt() *BalanceProductUpsertOne {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalanceProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceProductCreateBulk is the builder for creating many BalanceProduct entities in bulk.
type BalanceProductCreateBulk struct {
	config
	err      error
	builders []*BalanceProductCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceProduct entities in the database.
func (_c *BalanceProductCreateBulk) Save(ctx context.Context) ([]*BalanceProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceProductCreateBulk) SaveX(ctx context.Context) []*BalanceProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceProductUpsertBulk {
	_c.conflict = opts
	return &BalanceProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceProductCreateBulk) OnConflictColumns(columns ...string) *BalanceProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceProductUpsertBulk{
		create: _c,
	}
}

// BalanceProductUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceProduct nodes.
type BalanceProductUpsertBulk struct {
	create *BalanceProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceProductUpsertBulk) UpdateNewValues() *BalanceProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balanceproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceProductUpsertBulk) Ignore() *BalanceProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceProductUpsertBulk) DoNothing() *BalanceProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceProductCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceProductUpsertBulk) Update(set func(*BalanceProductUpsert)) *BalanceProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *BalanceProductUpsertBulk) SetName(v string) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateName() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *BalanceProductUpsertBulk) SetDescription(v string) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateDescription() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *BalanceProductUpsertBulk) SetPrice(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *BalanceProductUpsertBulk) AddPrice(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdatePrice() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdatePrice()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceProductUpsertBulk) SetAmount(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceProductUpsertBulk) AddAmount(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateAmount() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateAmount()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *BalanceProductUpsertBulk) SetOriginalPrice(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *BalanceProductUpsertBulk) AddOriginalPrice(v float64) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateOriginalPrice() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *BalanceProductUpsertBulk) ClearOriginalPrice() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetTags sets the "tags" field.
func (u *BalanceProductUpsertBulk) SetTags(v string) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateTags() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateTags()
	})
}

// SetFeatures sets the "features" field.
func (u *BalanceProductUpsertBulk) SetFeatures(v string) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateFeatures() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateFeatures()
	})
}

// SetProductName sets the "product_name" field.
func (u *BalanceProductUpsertBulk) SetProductName(v string) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateProductName() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateProductName()
	})
}

// SetForSale sets the "for_sale" field.
func (u *BalanceProductUpsertBulk) SetForSale(v bool) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateForSale() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateForSale()
	})
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (u *BalanceProductUpsertBulk) SetPurchaseLimit(v int) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetPurchaseLimit(v)
	})
}

// AddPurchaseLimit adds v to the "purchase_limit" field.
func (u *BalanceProductUpsertBulk) AddPurchaseLimit(v int) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddPurchaseLimit(v)
	})
}

// UpdatePurchaseLimit sets the "purchase_limit" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdatePurchaseLimit() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdatePurchaseLimit()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *BalanceProductUpsertBulk) SetSortOrder(v int) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *BalanceProductUpsertBulk) AddSortOrder(v int) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateSortOrder() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceProductUpsertBulk) SetUpdatedAt(v time.Time) *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceProductUpsertBulk) UpdateUpdatedAt() *BalanceProductUpsertBulk {
	return u.Update(func(s *BalanceProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalanceProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
