// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceproduct"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceProductDelete is the builder for deleting a BalanceProduct entity.
type BalanceProductDelete struct {
	config
	hooks    []Hook
	mutation *BalanceProductMutation
}

// Where appends a list predicates to the BalanceProductDelete builder.
func (_d *BalanceProductDelete) Where(ps ...predicate.BalanceProduct) *BalanceProductDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BalanceProductDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceProductDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BalanceProductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(balanceproduct.Table, sqlgraph.NewFieldSpec(balanceproduct.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BalanceProductDeleteOne is the builder for deleting a single BalanceProduct entity.
type BalanceProductDeleteOne struct {
	_d *BalanceProductDelete
}

// Where appends a list predicates to the BalanceProductDelete builder.
func (_d *BalanceProductDeleteOne) Where(ps ...predicate.BalanceProduct) *BalanceProductDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BalanceProductDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{balanceproduct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceProductDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
