// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceproduct"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceProductUpdate is the builder for updating BalanceProduct entities.
type BalanceProductUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceProductMutation
}

// Where appends a list predicates to the BalanceProductUpdate builder.
func (_u *BalanceProductUpdate) Where(ps ...predicate.BalanceProduct) *BalanceProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BalanceProductUpdate) SetName(v string) *BalanceProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableName(v *string) *BalanceProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceProductUpdate) SetDescription(v string) *BalanceProductUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableDescription(v *string) *BalanceProductUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BalanceProductUpdate) SetPrice(v float64) *BalanceProductUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillablePrice(v *float64) *BalanceProductUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BalanceProductUpdate) AddPrice(v float64) *BalanceProductUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceProductUpdate) SetAmount(v float64) *BalanceProductUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableAmount(v *float64) *BalanceProductUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceProductUpdate) AddAmount(v float64) *BalanceProductUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *BalanceProductUpdate) SetOriginalPrice(v float64) *BalanceProductUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableOriginalPrice(v *float64) *BalanceProductUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *BalanceProductUpdate) AddOriginalPrice(v float64) *BalanceProductUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *BalanceProductUpdate) ClearOriginalPrice() *BalanceProductUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetTags sets the "tags" field.
func (_u *BalanceProductUpdate) SetTags(v string) *BalanceProductUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableTags(v *string) *BalanceProductUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetFeatures sets the "features" field.
func (_u *BalanceProductUpdate) SetFeatures(v string) *BalanceProductUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableFeatures(v *string) *BalanceProductUpdate {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BalanceProductUpdate) SetProductName(v string) *BalanceProductUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableProductName(v *string) *BalanceProductUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BalanceProductUpdate) SetForSale(v bool) *BalanceProductUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableForSale(v *bool) *BalanceProductUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (_u *BalanceProductUpdate) SetPurchaseLimit(v int) *BalanceProductUpdate {
	_u.mutation.ResetPurchaseLimit()
	_u.mutation.SetPurchaseLimit(v)
	return _u
}

// SetNillablePurchaseLimit sets the "purchase_limit" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillablePurchaseLimit(v *int) *BalanceProductUpdate {
	if v != nil {
		_u.SetPurchaseLimit(*v)
	}
	return _u
}

// AddPurchaseLimit adds value to the "purchase_limit" field.
func (_u *BalanceProductUpdate) AddPurchaseLimit(v int) *BalanceProductUpdate {
	_u.mutation.AddPurchaseLimit(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BalanceProductUpdate) SetSortOrder(v int) *BalanceProductUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BalanceProductUpdate) SetNillableSortOrder(v *int) *BalanceProductUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BalanceProductUpdate) AddSortOrder(v int) *BalanceProductUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceProductUpdate) SetUpdatedAt(v time.Time) *BalanceProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BalanceProductMutation object of the builder.
func (_u *BalanceProductUpdate) Mutation() *BalanceProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceProductUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceProductUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balanceproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceProductUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := balanceproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := balanceproduct.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseLimit(); ok {
		if err := balanceproduct.PurchaseLimitValidator(v); err != nil {
			return &ValidationError{Name: "purchase_limit", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.purchase_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balanceproduct.Table, balanceproduct.Columns, sqlgraph.NewFieldSpec(balanceproduct.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balanceproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balanceproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(balanceproduct.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(balanceproduct.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balanceproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balanceproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(balanceproduct.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(balanceproduct.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(balanceproduct.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(balanceproduct.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(balanceproduct.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(balanceproduct.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(balanceproduct.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PurchaseLimit(); ok {
		_spec.SetField(balanceproduct.FieldPurchaseLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPurchaseLimit(); ok {
		_spec.AddField(balanceproduct.FieldPurchaseLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(balanceproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(balanceproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balanceproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceProductUpdateOne is the builder for updating a single BalanceProduct entity.
type BalanceProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceProductMutation
}

// SetName sets the "name" field.
func (_u *BalanceProductUpdateOne) SetName(v string) *BalanceProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableName(v *string) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceProductUpdateOne) SetDescription(v string) *BalanceProductUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableDescription(v *string) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *BalanceProductUpdateOne) SetPrice(v float64) *BalanceProductUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillablePrice(v *float64) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *BalanceProductUpdateOne) AddPrice(v float64) *BalanceProductUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceProductUpdateOne) SetAmount(v float64) *BalanceProductUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableAmount(v *float64) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceProductUpdateOne) AddAmount(v float64) *BalanceProductUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *BalanceProductUpdateOne) SetOriginalPrice(v float64) *BalanceProductUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableOriginalPrice(v *float64) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *BalanceProductUpdateOne) AddOriginalPrice(v float64) *BalanceProductUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *BalanceProductUpdateOne) ClearOriginalPrice() *BalanceProductUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetTags sets the "tags" field.
func (_u *BalanceProductUpdateOne) SetTags(v string) *BalanceProductUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableTags(v *string) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetFeatures sets the "features" field.
func (_u *BalanceProductUpdateOne) SetFeatures(v string) *BalanceProductUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableFeatures(v *string) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *BalanceProductUpdateOne) SetProductName(v string) *BalanceProductUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableProductName(v *string) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *BalanceProductUpdateOne) SetForSale(v bool) *BalanceProductUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableForSale(v *bool) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetPurchaseLimit sets the "purchase_limit" field.
func (_u *BalanceProductUpdateOne) SetPurchaseLimit(v int) *BalanceProductUpdateOne {
	_u.mutation.ResetPurchaseLimit()
	_u.mutation.SetPurchaseLimit(v)
	return _u
}

// SetNillablePurchaseLimit sets the "purchase_limit" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillablePurchaseLimit(v *int) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetPurchaseLimit(*v)
	}
	return _u
}

// AddPurchaseLimit adds value to the "purchase_limit" field.
func (_u *BalanceProductUpdateOne) AddPurchaseLimit(v int) *BalanceProductUpdateOne {
	_u.mutation.AddPurchaseLimit(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BalanceProductUpdateOne) SetSortOrder(v int) *BalanceProductUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BalanceProductUpdateOne) SetNillableSortOrder(v *int) *BalanceProductUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BalanceProductUpdateOne) AddSortOrder(v int) *BalanceProductUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceProductUpdateOne) SetUpdatedAt(v time.Time) *BalanceProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BalanceProductMutation object of the builder.
func (_u *BalanceProductUpdateOne) Mutation() *BalanceProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the BalanceProductUpdate builder.
func (_u *BalanceProductUpdateOne) Where(ps ...predicate.BalanceProduct) *BalanceProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceProductUpdateOne) Select(field string, fields ...string) *BalanceProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceProduct entity.
func (_u *BalanceProductUpdateOne) Save(ctx context.Context) (*BalanceProduct, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceProductUpdateOne) SaveX(ctx context.Context) *BalanceProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceProductUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balanceproduct.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceProductUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := balanceproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := balanceproduct.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PurchaseLimit(); ok {
		if err := balanceproduct.PurchaseLimitValidator(v); err != nil {
			return &ValidationError{Name: "purchase_limit", err: fmt.Errorf(`ent: validator failed for field "BalanceProduct.purchase_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceProductUpdateOne) sqlSave(ctx context.Context) (_node *BalanceProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balanceproduct.Table, balanceproduct.Columns, sqlgraph.NewFieldSpec(balanceproduct.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balanceproduct.FieldID)
		for _, f := range fields {
			if !balanceproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balanceproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(balanceproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balanceproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(balanceproduct.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(balanceproduct.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balanceproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balanceproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(balanceproduct.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(balanceproduct.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(balanceproduct.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(balanceproduct.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(balanceproduct.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(balanceproduct.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(balanceproduct.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PurchaseLimit(); ok {
		_spec.SetField(balanceproduct.FieldPurchaseLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPurchaseLimit(); ok {
		_spec.AddField(balanceproduct.FieldPurchaseLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(balanceproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(balanceproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BalanceProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balanceproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
