// Code generated by ent, DO NOT EDIT.

package balanceproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldPrice, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldAmount, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldOriginalPrice, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldTags, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldFeatures, v))
}

// ProductName applies equality check predicate on the "product_name" field. It's identical to ProductNameEQ.
func ProductName(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldProductName, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldForSale, v))
}

// PurchaseLimit applies equality check predicate on the "purchase_limit" field. It's identical to PurchaseLimitEQ.
func PurchaseLimit(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldPurchaseLimit, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldPrice, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldAmount, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotNull(FieldOriginalPrice))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasSuffix(FieldTags, v))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContainsFold(FieldTags, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContainsFold(FieldFeatures, v))
}

// ProductNameEQ applies the EQ predicate on the "product_name" field.
func ProductNameEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldProductName, v))
}

// ProductNameNEQ applies the NEQ predicate on the "product_name" field.
func ProductNameNEQ(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldProductName, v))
}

// ProductNameIn applies the In predicate on the "product_name" field.
func ProductNameIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldProductName, vs...))
}

// ProductNameNotIn applies the NotIn predicate on the "product_name" field.
func ProductNameNotIn(vs ...string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldProductName, vs...))
}

// ProductNameGT applies the GT predicate on the "product_name" field.
func ProductNameGT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldProductName, v))
}

// ProductNameGTE applies the GTE predicate on the "product_name" field.
func ProductNameGTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldProductName, v))
}

// ProductNameLT applies the LT predicate on the "product_name" field.
func ProductNameLT(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldProductName, v))
}

// ProductNameLTE applies the LTE predicate on the "product_name" field.
func ProductNameLTE(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldProductName, v))
}

// ProductNameContains applies the Contains predicate on the "product_name" field.
func ProductNameContains(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContains(FieldProductName, v))
}

// ProductNameHasPrefix applies the HasPrefix predicate on the "product_name" field.
func ProductNameHasPrefix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasPrefix(FieldProductName, v))
}

// ProductNameHasSuffix applies the HasSuffix predicate on the "product_name" field.
func ProductNameHasSuffix(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldHasSuffix(FieldProductName, v))
}

// ProductNameEqualFold applies the EqualFold predicate on the "product_name" field.
func ProductNameEqualFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEqualFold(FieldProductName, v))
}

// ProductNameContainsFold applies the ContainsFold predicate on the "product_name" field.
func ProductNameContainsFold(v string) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldContainsFold(FieldProductName, v))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldForSale, v))
}

// PurchaseLimitEQ applies the EQ predicate on the "purchase_limit" field.
func PurchaseLimitEQ(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldPurchaseLimit, v))
}

// PurchaseLimitNEQ applies the NEQ predicate on the "purchase_limit" field.
func PurchaseLimitNEQ(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldPurchaseLimit, v))
}

// PurchaseLimitIn applies the In predicate on the "purchase_limit" field.
func PurchaseLimitIn(vs ...int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldPurchaseLimit, vs...))
}

// PurchaseLimitNotIn applies the NotIn predicate on the "purchase_limit" field.
func PurchaseLimitNotIn(vs ...int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldPurchaseLimit, vs...))
}

// PurchaseLimitGT applies the GT predicate on the "purchase_limit" field.
func PurchaseLimitGT(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldPurchaseLimit, v))
}

// PurchaseLimitGTE applies the GTE predicate on the "purchase_limit" field.
func PurchaseLimitGTE(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldPurchaseLimit, v))
}

// PurchaseLimitLT applies the LT predicate on the "purchase_limit" field.
func PurchaseLimitLT(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldPurchaseLimit, v))
}

// PurchaseLimitLTE applies the LTE predicate on the "purchase_limit" field.
func PurchaseLimitLTE(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldPurchaseLimit, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceProduct) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceProduct) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceProduct) predicate.BalanceProduct {
	return predicate.BalanceProduct(sql.NotPredicates(p))
}
